name: CI/CD Pipeline

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest mypy black isort
          if [ -f requirements.txt ]; then pip install -r practice/requirements.txt; fi
      - name: unittest
        run: |
          pytest practice/tests/
      # - name: flake8
      #   run: |
      #     flake8 practice/src/
      # - name: mypy
      #   run: |
      #     mypy practice/src/
      - name: black
        run: |
          black --diff --check practice/src/
      - name: isort
        run: |
          isort --check-only practice/src/
